name: Test pipeline

on:
  # push:
  #   branches:
  #     - development
  pull_request:
    branches:
      # - main  
      - development   
      # - 'release/**'       
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  test-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}
      # DATABRICKS_JOBS_API_VERSION: 2.1

    steps:
      # - uses: actions/checkout@v1
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis   

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.9

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -r unit-requirements.txt
          pip install -e .

      # - name: Export Databricks jobs api 2.1
      #   run: |
      #     export DATABRICKS_JOBS_API_VERSION=2.1
        
      - name: Run pylint code analysis
        run: |
          echo "Launching pylint code analysis"
          pylint --exit-zero cicd_databricks_github/ tests/ -r n --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" > pylint_report.txt      

      # - name: Run unit tests
      #   run: |
      #     echo "Launching unit tests"
      #     make test   

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      # TODO: deploy files to workspace
      # - name: Deploy notebooks
      #   shell: bash
      #   run: |
      #     echo "Deploying notebooks"
      #     databricks workspace import_dir --overwrite notebooks/ /Released/notebook/              



