name: Release pipeline

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches:  
      - 'release/**'         


jobs:
  release-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.7 ]

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies and project in dev mode
        run: |
          pip install -r unit-requirements.txt

      - name: Deploy integration test
        run: |
          dbx deploy --jobs=cicd-databricks-github-sample-integration-test --files-only

      - name: Run integration test
        run: |
          dbx launch --job=cicd-databricks-github-sample-integration-test --as-run-submit --trace          

      - name: Deploy the job
        run: |
          dbx deploy --jobs=cicd-databricks-github-sample --files-only

      - name: Run the job
        run: |
          dbx launch --job=cicd-databricks-github-sample --as-run-submit --trace          

      # - name: Create Release
      #   id: create_release
      #   uses: actions/create-release@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions
      #   with:
      #     tag_name: ${{ github.ref }}
      #     release_name: Release ${{ github.ref }}
      #     body: |
      #       Release for version ${{ github.ref }}.
      #     draft: false
      #     prerelease: false


